var searchData=
[
  ['iargbasecontainer_2216',['IArgBaseContainer',['../interface_zero_install_1_1_model_1_1_i_arg_base_container.html',1,'ZeroInstall::Model']]],
  ['ibindingcontainer_2217',['IBindingContainer',['../interface_zero_install_1_1_model_1_1_i_binding_container.html',1,'ZeroInstall::Model']]],
  ['icatalogmanager_2218',['ICatalogManager',['../interface_zero_install_1_1_services_1_1_feeds_1_1_i_catalog_manager.html',1,'ZeroInstall::Services::Feeds']]],
  ['icategoryintegrationmanager_2219',['ICategoryIntegrationManager',['../interface_zero_install_1_1_desktop_integration_1_1_i_category_integration_manager.html',1,'ZeroInstall::DesktopIntegration']]],
  ['ichangenotify_2220',['IChangeNotify',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_change_notify.html',1,'NanoByte::Common']]],
  ['iclisubcommand_2221',['ICliSubCommand',['../interface_zero_install_1_1_commands_1_1_i_cli_sub_command.html',1,'ZeroInstall::Commands']]],
  ['icloneable_2222',['ICloneable',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'NanoByte::Common']]],
  ['icloneable_3c_20accesspoint_20_3e_2223',['ICloneable&lt; AccessPoint &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'NanoByte::Common']]],
  ['icloneable_3c_20accesspointlist_20_3e_2224',['ICloneable&lt; AccessPointList &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'NanoByte::Common']]],
  ['icloneable_3c_20appentry_20_3e_2225',['ICloneable&lt; AppEntry &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'NanoByte::Common']]],
  ['icloneable_3c_20applist_20_3e_2226',['ICloneable&lt; AppList &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'NanoByte::Common']]],
  ['icloneable_3c_20arg_20_3e_2227',['ICloneable&lt; Arg &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'NanoByte::Common']]],
  ['icloneable_3c_20argbase_20_3e_2228',['ICloneable&lt; ArgBase &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'NanoByte::Common']]],
  ['icloneable_3c_20autoplayevent_20_3e_2229',['ICloneable&lt; AutoPlayEvent &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'NanoByte::Common']]],
  ['icloneable_3c_20binding_20_3e_2230',['ICloneable&lt; Binding &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'NanoByte::Common']]],
  ['icloneable_3c_20capability_20_3e_2231',['ICloneable&lt; Capability &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'NanoByte::Common']]],
  ['icloneable_3c_20capabilitylist_20_3e_2232',['ICloneable&lt; CapabilityList &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'NanoByte::Common']]],
  ['icloneable_3c_20catalog_20_3e_2233',['ICloneable&lt; Catalog &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'NanoByte::Common']]],
  ['icloneable_3c_20category_20_3e_2234',['ICloneable&lt; Category &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'NanoByte::Common']]],
  ['icloneable_3c_20command_20_3e_2235',['ICloneable&lt; Command &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'NanoByte::Common']]],
  ['icloneable_3c_20config_20_3e_2236',['ICloneable&lt; Config &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'NanoByte::Common']]],
  ['icloneable_3c_20constraint_20_3e_2237',['ICloneable&lt; Constraint &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'NanoByte::Common']]],
  ['icloneable_3c_20dependency_20_3e_2238',['ICloneable&lt; Dependency &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'NanoByte::Common']]],
  ['icloneable_3c_20domain_20_3e_2239',['ICloneable&lt; Domain &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'NanoByte::Common']]],
  ['icloneable_3c_20element_20_3e_2240',['ICloneable&lt; Element &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'NanoByte::Common']]],
  ['icloneable_3c_20entrypoint_20_3e_2241',['ICloneable&lt; EntryPoint &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'NanoByte::Common']]],
  ['icloneable_3c_20feed_20_3e_2242',['ICloneable&lt; Feed &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'NanoByte::Common']]],
  ['icloneable_3c_20feedpreferences_20_3e_2243',['ICloneable&lt; FeedPreferences &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'NanoByte::Common']]],
  ['icloneable_3c_20feedreference_20_3e_2244',['ICloneable&lt; FeedReference &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'NanoByte::Common']]],
  ['icloneable_3c_20filetypeextension_20_3e_2245',['ICloneable&lt; FileTypeExtension &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'NanoByte::Common']]],
  ['icloneable_3c_20icon_20_3e_2246',['ICloneable&lt; Icon &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'NanoByte::Common']]],
  ['icloneable_3c_20implementationpreferences_20_3e_2247',['ICloneable&lt; ImplementationPreferences &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'NanoByte::Common']]],
  ['icloneable_3c_20implementationselection_20_3e_2248',['ICloneable&lt; ImplementationSelection &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'NanoByte::Common']]],
  ['icloneable_3c_20interfacepreferences_20_3e_2249',['ICloneable&lt; InterfacePreferences &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'NanoByte::Common']]],
  ['icloneable_3c_20interfacereference_20_3e_2250',['ICloneable&lt; InterfaceReference &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'NanoByte::Common']]],
  ['icloneable_3c_20irecipestep_20_3e_2251',['ICloneable&lt; IRecipeStep &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'NanoByte::Common']]],
  ['icloneable_3c_20key_20_3e_2252',['ICloneable&lt; Key &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'NanoByte::Common']]],
  ['icloneable_3c_20knownprotocolprefix_20_3e_2253',['ICloneable&lt; KnownProtocolPrefix &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'NanoByte::Common']]],
  ['icloneable_3c_20localizablestring_20_3e_2254',['ICloneable&lt; LocalizableString &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'']]],
  ['icloneable_3c_20localizablestringcollection_20_3e_2255',['ICloneable&lt; LocalizableStringCollection &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'']]],
  ['icloneable_3c_20requirements_20_3e_2256',['ICloneable&lt; Requirements &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'NanoByte::Common']]],
  ['icloneable_3c_20restriction_20_3e_2257',['ICloneable&lt; Restriction &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'NanoByte::Common']]],
  ['icloneable_3c_20retrievalmethod_20_3e_2258',['ICloneable&lt; RetrievalMethod &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'NanoByte::Common']]],
  ['icloneable_3c_20selections_20_3e_2259',['ICloneable&lt; Selections &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'NanoByte::Common']]],
  ['icloneable_3c_20trustdb_20_3e_2260',['ICloneable&lt; TrustDB &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'NanoByte::Common']]],
  ['icloneable_3c_20verb_20_3e_2261',['ICloneable&lt; Verb &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'NanoByte::Common']]],
  ['icloneable_3c_20workingdir_20_3e_2262',['ICloneable&lt; WorkingDir &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'NanoByte::Common']]],
  ['icloneable_3c_20xmldictionary_20_3e_2263',['ICloneable&lt; XmlDictionary &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'']]],
  ['icloneable_3c_20xmldictionaryentry_20_3e_2264',['ICloneable&lt; XmlDictionaryEntry &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'']]],
  ['icommandexecutor_2265',['ICommandExecutor',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_undo_1_1_i_command_executor.html',1,'NanoByte::Common::Undo']]],
  ['icommandhandler_2266',['ICommandHandler',['../interface_zero_install_1_1_commands_1_1_i_command_handler.html',1,'ZeroInstall::Commands']]],
  ['icommandmanager_2267',['ICommandManager',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_undo_1_1_i_command_manager.html',1,'NanoByte::Common::Undo']]],
  ['icon_2268',['Icon',['../class_zero_install_1_1_model_1_1_icon.html',1,'ZeroInstall::Model']]],
  ['iconaccesspoint_2269',['IconAccessPoint',['../class_zero_install_1_1_desktop_integration_1_1_access_points_1_1_icon_access_point.html',1,'ZeroInstall::DesktopIntegration::AccessPoints']]],
  ['iconcapability_2270',['IconCapability',['../class_zero_install_1_1_model_1_1_capabilities_1_1_icon_capability.html',1,'ZeroInstall::Model::Capabilities']]],
  ['iconcapabilitymodel_2271',['IconCapabilityModel',['../class_zero_install_1_1_desktop_integration_1_1_view_model_1_1_icon_capability_model.html',1,'ZeroInstall::DesktopIntegration::ViewModel']]],
  ['iconmimetypeconverter_2272',['IconMimeTypeConverter',['../class_zero_install_1_1_model_1_1_design_1_1_icon_mime_type_converter.html',1,'ZeroInstall::Model::Design']]],
  ['iconstore_2273',['IconStore',['../class_zero_install_1_1_store_1_1_icon_store.html',1,'ZeroInstall::Store']]],
  ['icontextmenu_2274',['IContextMenu',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_controls_1_1_i_context_menu.html',1,'NanoByte::Common::Controls']]],
  ['icredentialprovider_2275',['ICredentialProvider',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_net_1_1_i_credential_provider.html',1,'NanoByte::Common::Net']]],
  ['idependencycontainer_2276',['IDependencyContainer',['../interface_zero_install_1_1_model_1_1_i_dependency_container.html',1,'ZeroInstall::Model']]],
  ['idescriptioncontainer_2277',['IDescriptionContainer',['../interface_zero_install_1_1_model_1_1_i_description_container.html',1,'ZeroInstall::Model']]],
  ['ieditordialog_2278',['IEditorDialog',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_controls_1_1_i_editor_dialog.html',1,'NanoByte::Common::Controls']]],
  ['ielementcontainer_2279',['IElementContainer',['../interface_zero_install_1_1_model_1_1_i_element_container.html',1,'ZeroInstall::Model']]],
  ['ienvironmentbuilder_2280',['IEnvironmentBuilder',['../interface_zero_install_1_1_services_1_1_executors_1_1_i_environment_builder.html',1,'ZeroInstall::Services::Executors']]],
  ['iexecutor_2281',['IExecutor',['../interface_zero_install_1_1_services_1_1_executors_1_1_i_executor.html',1,'ZeroInstall::Services::Executors']]],
  ['ifeedcache_2282',['IFeedCache',['../interface_zero_install_1_1_store_1_1_feeds_1_1_i_feed_cache.html',1,'ZeroInstall::Store::Feeds']]],
  ['ifeedmanager_2283',['IFeedManager',['../interface_zero_install_1_1_services_1_1_feeds_1_1_i_feed_manager.html',1,'ZeroInstall::Services::Feeds']]],
  ['ifetcher_2284',['IFetcher',['../interface_zero_install_1_1_services_1_1_fetchers_1_1_i_fetcher.html',1,'ZeroInstall::Services::Fetchers']]],
  ['ifingerprintcontainer_2285',['IFingerprintContainer',['../interface_zero_install_1_1_store_1_1_trust_1_1_i_fingerprint_container.html',1,'ZeroInstall::Store::Trust']]],
  ['ihighlightcolor_2286',['IHighlightColor',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_controls_1_1_i_highlight_color.html',1,'NanoByte::Common::Controls']]],
  ['iiconcontainer_2287',['IIconContainer',['../interface_zero_install_1_1_model_1_1_i_icon_container.html',1,'ZeroInstall.Model.IIconContainer'],['../interface_zero_install_1_1_publish_1_1_entry_points_1_1_i_icon_container.html',1,'ZeroInstall.Publish.EntryPoints.IIconContainer']]],
  ['iiconstore_2288',['IIconStore',['../interface_zero_install_1_1_store_1_1_i_icon_store.html',1,'ZeroInstall::Store']]],
  ['iimplementationstore_2289',['IImplementationStore',['../interface_zero_install_1_1_store_1_1_implementations_1_1_i_implementation_store.html',1,'ZeroInstall::Store::Implementations']]],
  ['iintegrationmanager_2290',['IIntegrationManager',['../interface_zero_install_1_1_desktop_integration_1_1_i_integration_manager.html',1,'ZeroInstall::DesktopIntegration']]],
  ['iinterfaceuri_2291',['IInterfaceUri',['../interface_zero_install_1_1_model_1_1_i_interface_uri.html',1,'ZeroInstall::Model']]],
  ['iinterfaceuribindingcontainer_2292',['IInterfaceUriBindingContainer',['../interface_zero_install_1_1_model_1_1_i_interface_uri_binding_container.html',1,'ZeroInstall::Model']]],
  ['ikeyidcontainer_2293',['IKeyIDContainer',['../interface_zero_install_1_1_store_1_1_trust_1_1_i_key_i_d_container.html',1,'ZeroInstall::Store::Trust']]],
  ['imagedatadirectory_2294',['ImageDataDirectory',['../struct_zero_install_1_1_publish_1_1_entry_points_1_1_image_data_directory.html',1,'ZeroInstall::Publish::EntryPoints']]],
  ['imagedosheader_2295',['ImageDosHeader',['../struct_zero_install_1_1_publish_1_1_entry_points_1_1_image_dos_header.html',1,'ZeroInstall::Publish::EntryPoints']]],
  ['imagefileheader_2296',['ImageFileHeader',['../struct_zero_install_1_1_publish_1_1_entry_points_1_1_image_file_header.html',1,'ZeroInstall::Publish::EntryPoints']]],
  ['imageoptionalheader32_2297',['ImageOptionalHeader32',['../struct_zero_install_1_1_publish_1_1_entry_points_1_1_image_optional_header32.html',1,'ZeroInstall::Publish::EntryPoints']]],
  ['imageoptionalheader64_2298',['ImageOptionalHeader64',['../struct_zero_install_1_1_publish_1_1_entry_points_1_1_image_optional_header64.html',1,'ZeroInstall::Publish::EntryPoints']]],
  ['imergeable_2299',['IMergeable',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_dispatch_1_1_i_mergeable.html',1,'NanoByte::Common::Dispatch']]],
  ['imergeable_3c_20appentry_20_3e_2300',['IMergeable&lt; AppEntry &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_dispatch_1_1_i_mergeable.html',1,'NanoByte::Common::Dispatch']]],
  ['imergeable_3c_20zeroinstall_3a_3adesktopintegration_3a_3aappentry_20_3e_2301',['IMergeable&lt; ZeroInstall::DesktopIntegration::AppEntry &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_dispatch_1_1_i_mergeable.html',1,'NanoByte::Common::Dispatch']]],
  ['implementation_2302',['Implementation',['../class_zero_install_1_1_model_1_1_implementation.html',1,'ZeroInstall::Model']]],
  ['implementationalreadyinstoreexception_2303',['ImplementationAlreadyInStoreException',['../class_zero_install_1_1_store_1_1_implementations_1_1_implementation_already_in_store_exception.html',1,'ZeroInstall::Store::Implementations']]],
  ['implementationbase_2304',['ImplementationBase',['../class_zero_install_1_1_model_1_1_implementation_base.html',1,'ZeroInstall::Model']]],
  ['implementationnode_2305',['ImplementationNode',['../class_zero_install_1_1_store_1_1_view_model_1_1_implementation_node.html',1,'ZeroInstall::Store::ViewModel']]],
  ['implementationnotfoundexception_2306',['ImplementationNotFoundException',['../class_zero_install_1_1_store_1_1_implementations_1_1_implementation_not_found_exception.html',1,'ZeroInstall::Store::Implementations']]],
  ['implementationpreferences_2307',['ImplementationPreferences',['../class_zero_install_1_1_model_1_1_preferences_1_1_implementation_preferences.html',1,'ZeroInstall::Model::Preferences']]],
  ['implementationselection_2308',['ImplementationSelection',['../class_zero_install_1_1_model_1_1_selection_1_1_implementation_selection.html',1,'ZeroInstall::Model::Selection']]],
  ['implementationstores_2309',['ImplementationStores',['../class_zero_install_1_1_store_1_1_implementations_1_1_implementation_stores.html',1,'ZeroInstall::Store::Implementations']]],
  ['implementationstoreutils_2310',['ImplementationStoreUtils',['../class_zero_install_1_1_store_1_1_implementations_1_1_implementation_store_utils.html',1,'ZeroInstall::Store::Implementations']]],
  ['implementationutils_2311',['ImplementationUtils',['../class_zero_install_1_1_publish_1_1_implementation_utils.html',1,'ZeroInstall::Publish']]],
  ['implementationversion_2312',['ImplementationVersion',['../class_zero_install_1_1_model_1_1_implementation_version.html',1,'ZeroInstall::Model']]],
  ['import_2313',['Import',['../class_zero_install_1_1_commands_1_1_basic_1_1_import.html',1,'ZeroInstall::Commands::Basic']]],
  ['importapps_2314',['ImportApps',['../class_zero_install_1_1_commands_1_1_desktop_1_1_import_apps.html',1,'ZeroInstall::Commands::Desktop']]],
  ['inamed_2315',['INamed',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_named.html',1,'NanoByte::Common']]],
  ['inamed_3c_20cachenode_20_3e_2316',['INamed&lt; CacheNode &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_named.html',1,'NanoByte::Common']]],
  ['inamed_3c_20selectionstreenode_20_3e_2317',['INamed&lt; SelectionsTreeNode &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_named.html',1,'NanoByte::Common']]],
  ['inamed_3c_20trustnode_20_3e_2318',['INamed&lt; TrustNode &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_named.html',1,'NanoByte::Common']]],
  ['inputbox_2319',['InputBox',['https://common.nano-byte.net/class_nano_byte_1_1_common_1_1_controls_1_1_input_box.html',1,'NanoByte::Common::Controls']]],
  ['inspectionform_2320',['InspectionForm',['https://common.nano-byte.net/class_nano_byte_1_1_common_1_1_controls_1_1_inspection_form.html',1,'NanoByte::Common::Controls']]],
  ['installcommands_2321',['InstallCommands',['../struct_zero_install_1_1_model_1_1_capabilities_1_1_install_commands.html',1,'ZeroInstall::Model::Capabilities']]],
  ['installcommandsconverter_2322',['InstallCommandsConverter',['../class_zero_install_1_1_model_1_1_design_1_1_install_commands_converter.html',1,'ZeroInstall::Model::Design']]],
  ['integrateapp_2323',['IntegrateApp',['../class_zero_install_1_1_commands_1_1_desktop_1_1_integrate_app.html',1,'ZeroInstall::Commands::Desktop']]],
  ['integrationcommand_2324',['IntegrationCommand',['../class_zero_install_1_1_commands_1_1_desktop_1_1_integration_command.html',1,'ZeroInstall::Commands::Desktop']]],
  ['integrationmanager_2325',['IntegrationManager',['../class_zero_install_1_1_desktop_integration_1_1_integration_manager.html',1,'ZeroInstall::DesktopIntegration']]],
  ['integrationmanagerbase_2326',['IntegrationManagerBase',['../class_zero_install_1_1_desktop_integration_1_1_integration_manager_base.html',1,'ZeroInstall::DesktopIntegration']]],
  ['integrationstate_2327',['IntegrationState',['../class_zero_install_1_1_desktop_integration_1_1_view_model_1_1_integration_state.html',1,'ZeroInstall::DesktopIntegration::ViewModel']]],
  ['interfacepreferences_2328',['InterfacePreferences',['../class_zero_install_1_1_model_1_1_preferences_1_1_interface_preferences.html',1,'ZeroInstall::Model::Preferences']]],
  ['interfacereference_2329',['InterfaceReference',['../class_zero_install_1_1_model_1_1_interface_reference.html',1,'ZeroInstall::Model']]],
  ['interpretedscript_2330',['InterpretedScript',['../class_zero_install_1_1_publish_1_1_entry_points_1_1_interpreted_script.html',1,'ZeroInstall::Publish::EntryPoints']]],
  ['iopenpgp_2331',['IOpenPgp',['../interface_zero_install_1_1_store_1_1_trust_1_1_i_open_pgp.html',1,'ZeroInstall::Store::Trust']]],
  ['ipackagemanager_2332',['IPackageManager',['../interface_zero_install_1_1_services_1_1_native_1_1_i_package_manager.html',1,'ZeroInstall::Services::Native']]],
  ['iprogress_2333',['IProgress',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_tasks_1_1_i_progress.html',1,'NanoByte::Common::Tasks']]],
  ['iprogress_3c_20nanobyte_3a_3acommon_3a_3atasks_3a_3atasksnapshot_20_3e_2334',['IProgress&lt; NanoByte::Common::Tasks::TaskSnapshot &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_tasks_1_1_i_progress.html',1,'']]],
  ['iprogress_3c_20tasksnapshot_20_3e_2335',['IProgress&lt; TaskSnapshot &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_tasks_1_1_i_progress.html',1,'']]],
  ['irecipestep_2336',['IRecipeStep',['../interface_zero_install_1_1_model_1_1_i_recipe_step.html',1,'ZeroInstall::Model']]],
  ['iselectioncandidateprovider_2337',['ISelectionCandidateProvider',['../interface_zero_install_1_1_services_1_1_solvers_1_1_i_selection_candidate_provider.html',1,'ZeroInstall::Services::Solvers']]],
  ['iselectionsmanager_2338',['ISelectionsManager',['../interface_zero_install_1_1_services_1_1_i_selections_manager.html',1,'ZeroInstall::Services']]],
  ['ishelllink_2339',['IShellLink',['../interface_zero_install_1_1_desktop_integration_1_1_windows_1_1_shortcut_1_1_i_shell_link.html',1,'ZeroInstall::DesktopIntegration::Windows::Shortcut']]],
  ['isolver_2340',['ISolver',['../interface_zero_install_1_1_services_1_1_solvers_1_1_i_solver.html',1,'ZeroInstall::Services::Solvers']]],
  ['isummarycontainer_2341',['ISummaryContainer',['../interface_zero_install_1_1_model_1_1_i_summary_container.html',1,'ZeroInstall::Model']]],
  ['itask_2342',['ITask',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_tasks_1_1_i_task.html',1,'NanoByte::Common::Tasks']]],
  ['itaskhandler_2343',['ITaskHandler',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_tasks_1_1_i_task_handler.html',1,'NanoByte::Common::Tasks']]],
  ['itouchcontrol_2344',['ITouchControl',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_controls_1_1_i_touch_control.html',1,'NanoByte::Common::Controls']]],
  ['itrustmanager_2345',['ITrustManager',['../interface_zero_install_1_1_services_1_1_feeds_1_1_i_trust_manager.html',1,'ZeroInstall::Services::Feeds']]],
  ['iundocommand_2346',['IUndoCommand',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_undo_1_1_i_undo_command.html',1,'NanoByte::Common::Undo']]],
  ['ivaluecommand_2347',['IValueCommand',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_undo_1_1_i_value_command.html',1,'NanoByte::Common::Undo']]],
  ['iwizardpage_2348',['IWizardPage',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_controls_1_1_i_wizard_page.html',1,'NanoByte::Common::Controls']]]
];
